### ISSUE TITLE
Suggestion: Wrapper type and distance function

### ISSUE THREAD

**Issue by chrysn** [jaehl/blockhash#1]
(Off topic, but first of all: Thanks for starting this, it's great to see a Rust implementation of something I've just started looking into spring up right in that time).

When hashes of images are created as `[u8; n]`, they are hard to compare, as no function for their hamming distance is immediately available.

I think it would be useful to have the blockhash functions return some BlockHash type (probably a plain wrapper around the [u8; n] it returns now) that would have
* a method for reading the [u8; n]
* a method for formatting as a hex string (possibly implementing Display)
* a method `fn distance(&self, other: &Self) -> usize` that gives easy access to the hamming distance used for evaluating a comparison

**Comment by jaehl** [comment]
Sounds like a good idea to me. I'll make an update soon.

**Comment by jaehl** [comment]
Version 0.2.0 now uses wrapper types (e.g. [Blockhash64](https://docs.rs/blockhash/0.2.0/blockhash/struct.Blockhash64.html)).
